<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TomodachiDrawerCn.Contracts\TomodachiDrawerCn.Contracts.csproj" />
    <ProjectReference Include="..\..\TomodachiDrawer.Core\TomodachiDrawer.Core.csproj" />
  </ItemGroup>
</Project>
